
import { ProductCategory, Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: ProductCategory.All, arabicName: "الكل" },
  { id: ProductCategory.Chargers, arabicName: "شواحن" },
  { id: ProductCategory.Cables, arabicName: "وصلات" },
  { id: ProductCategory.FlashDrives, arabicName: "فلاشات" },
  { id: ProductCategory.Keyboards, arabicName: "لوحة مفاتيح" },
  { id: ProductCategory.BluetoothHeadphones, arabicName: "سماعات بلوتوث" },
  { id: ProductCategory.WiredHeadphones, arabicName: "سماعات سلكية" },
  { id: ProductCategory.ComputerSpeakers, arabicName: "سماعات كمبيوتر" },
  { id: ProductCategory.MobileCases, arabicName: "جرابات موبايل" },
  { id: ProductCategory.Mice, arabicName: "ماوس" },
  { id: ProductCategory.Other, arabicName: "اكسسوارات أخرى" },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Fast Charger Pro",
    arabicName: "شاحن سريع برو",
    category: ProductCategory.Chargers,
    price: 120,
    imageUrl: "https://picsum.photos/seed/charger1/400/300",
    rating: 4.5,
    reviews: 150,
    isNew: true,
  },
  {
    id: "2",
    name: "USB-C Cable Nylon Braided",
    arabicName: "كابل USB-C نايلون مجدول",
    category: ProductCategory.Cables,
    price: 60,
    imageUrl: "https://picsum.photos/seed/cable1/400/300",
    rating: 4.2,
    reviews: 90,
  },
  {
    id: "3",
    name: "128GB Flash Drive",
    arabicName: "فلاش ميموري 128 جيجا",
    category: ProductCategory.FlashDrives,
    price: 150,
    imageUrl: "https://picsum.photos/seed/flash1/400/300",
    rating: 4.8,
    reviews: 200,
    discountPrice: 130,
  },
  {
    id: "4",
    name: "Mechanical Gaming Keyboard",
    arabicName: "لوحة مفاتيح ميكانيكية للألعاب",
    category: ProductCategory.Keyboards,
    price: 350,
    imageUrl: "https://picsum.photos/seed/keyboard1/400/300",
    rating: 4.7,
    reviews: 120,
  },
  {
    id: "5",
    name: "Noise Cancelling Bluetooth Headphones",
    arabicName: "سماعات بلوتوث عازلة للضوضاء",
    category: ProductCategory.BluetoothHeadphones,
    price: 450,
    imageUrl: "https://picsum.photos/seed/btheadphones1/400/300",
    rating: 4.9,
    reviews: 300,
    isNew: true,
  },
  {
    id: "6",
    name: "In-Ear Wired Headphones",
    arabicName: "سماعات سلكية داخل الأذن",
    category: ProductCategory.WiredHeadphones,
    price: 80,
    imageUrl: "https://picsum.photos/seed/wiredheadphones1/400/300",
    rating: 4.0,
    reviews: 75,
  },
  {
    id: "7",
    name: "2.1 Computer Speakers",
    arabicName: "سماعات كمبيوتر 2.1",
    category: ProductCategory.ComputerSpeakers,
    price: 280,
    imageUrl: "https://picsum.photos/seed/speakers1/400/300",
    rating: 4.3,
    reviews: 60,
  },
  {
    id: "8",
    name: "Silicone Mobile Case iPhone 15",
    arabicName: "جراب سيليكون لآيفون 15",
    category: ProductCategory.MobileCases,
    price: 90,
    imageUrl: "https://picsum.photos/seed/case1/400/300",
    rating: 4.6,
    reviews: 180,
    discountPrice: 75,
  },
  {
    id: "9",
    name: "Wireless Ergonomic Mouse",
    arabicName: "ماوس لاسلكي مريح",
    category: ProductCategory.Mice,
    price: 180,
    imageUrl: "https://picsum.photos/seed/mouse1/400/300",
    rating: 4.4,
    reviews: 110,
  },
  {
    id: "10",
    name: "Universal Phone Holder",
    arabicName: "حامل هاتف عالمي",
    category: ProductCategory.Other,
    price: 70,
    imageUrl: "https://picsum.photos/seed/holder1/400/300",
    rating: 4.1,
    reviews: 50,
    isNew: true,
  },
  {
    id: "11",
    name: "Power Bank 10000mAh",
    arabicName: "باور بانك 10000 مللي أمبير",
    category: ProductCategory.Chargers,
    price: 200,
    imageUrl: "https://picsum.photos/seed/powerbank1/400/300",
    rating: 4.7,
    reviews: 220,
  },
  {
    id: "12",
    name: "HDMI Cable 2M",
    arabicName: "كابل HDMI طول 2 متر",
    category: ProductCategory.Cables,
    price: 95,
    imageUrl: "https://picsum.photos/seed/hdmicable/400/300",
    rating: 4.3,
    reviews: 85,
  }
];
